<a href="https://colab.research.google.com/github/Lezhenkov/ISII/blob/main/%D0%9B%D0%A0_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import random
import time
import math as mt
import pandas as pd

## Часть 1: генерация одномерного массива с помощью numpy и встроенных средств python

Для данной задачи при выводе массива ограничимся 10 элементами: 5 первых и 5 последних. При обычном выводе возникла проблема с google colab. При попытке напечатать массив в 100.000 элементов с помощью встроенных средств: система сообщала о перегрузке памяти консоли. В связи с этим и для удобства восприятия и были наложены ограничения

In [ ]:
def gener_d1_massive_np():
  # Пользователь вводит исходные данные:
  x, a, b = int(input("введите число элементов массива ")), int(
      input('введите левую границу массива ')), int(input('введите правую границу массива '))
  tic = time.perf_counter_ns()  # запуск таймера
  # Добавляем элементы в массив. Данное выражение требуется для учета границ, введенных пользователем
  d1 = (b-a) * np.random.sample(x) + a 
  tac = time.perf_counter_ns() # остановка таймера
  # для удобства чтения и защиты от ошибок вводим условие на вывод массива, чтобы не засорять консоль ненужными данными
  if len(d1) > 10:
    print("Random number list is : ", d1[0:5], '...', d1[-6:-1], sep = '\n')
  else:
    print ("Random number list is : ", d1, sep = '\n')  # выводим массив пользователю
  # находим и выводим время, затраченное на генерацию массива в наносекундах 
  print(f"Создание массива заняло {tac-tic} нсек") 
  pass


def gener_d1_massive_np_poor():
  # Пользователь вводит исходные данные:
  x = int(input("введите число элементов массива "))
  tic = time.perf_counter_ns()  # записываем первое значение таймера
  # Добавляем элементы в массив. Данное выражение требуется для учета границ, введенных пользователем
  d1 = np.random.sample(x)
  tac = time.perf_counter_ns() # записываем второе
  # цикл для ограничения вывода
  if len(d1) > 10:
    print("Random number list is : ", d1[0:5], '...', d1[-6:-1], sep = '\n')
  else:
    print ("Random number list is : ", d1, sep = '\n')  # выводим массив пользователю
  # находим и выводим время, затраченное на генерацию массива в наносекундах 
  print(f"Создание массива заняло {tac-tic} нсек") 
  pass


def gener_d1_massive_py():
  # пользователь вводит исходные данные
  x, a, b = int(input("введите число элементов массива ")), int(
      input('введите левую границу массива ')), int(input('введите правую границу массива '))
  tic = time.perf_counter_ns() # старт таймера
  d1 = [] # создаем пустой массив, куда будем добавлять элементы 
  # запускаем цикл по добавлению элементов 
  for i in range(x):   # диапазоном для цикла является введеный пользователем x - длина массива
    d1.append(random.uniform(a,b)) # внутри цикла добавляем элементы по одному, указывая границы генерации случайного числа
  tac = time.perf_counter_ns()
  if len(d1) > 10:
    print("Random number list is : ", d1[0:5], '...', d1[-6:-1], sep = '\n')
  else:
    print ("Random number list is : ", d1, sep = '\n')  # выводим массив пользователю
  print(f"Создание массива заняло {tac-tic} нсек")
  pass

In [ ]:
print(gener_d1_massive_np())

введите число элементов массива 100
введите левую границу массива 0
введите правую границу массива 1
Random number list is : 
[0.3082573  0.20757354 0.38415426 0.46963012 0.45041049]
...
[0.02589004 0.76584761 0.45040736 0.79306554 0.79894706]
Создание массива заняло 94130 нсек
None


In [ ]:
print(gener_d1_massive_np_poor())

введите число элементов массива 100
Random number list is : 
[0.3251955  0.56594332 0.65675961 0.46296617 0.44568103]
...
[0.60079574 0.56253883 0.23399534 0.55246769 0.30576486]
Создание массива заняло 30170 нсек
None


In [ ]:
print(gener_d1_massive_py())

введите число элементов массива 100
введите левую границу массива 0
введите правую границу массива 1
Random number list is : 
[0.850411038258446, 0.22985238919030915, 0.4524664920015924, 0.0954545877352454, 0.0665477642775052]
...
[0.3626179105399968, 0.7972060348329624, 0.5647804767972265, 0.39898925311171896, 0.5695721781095684]
Создание массива заняло 72100 нсек
None


Следует обратить внимание, что при генерации с помощью numpy было использовано 2 функции. Разница заключается в том, что функция gener_d1_massive_np() имеет возможность ручного задавания границ, а gener_d1_massive_np_poor() данной возможности не имеет, а выводит числа в диапозоне [0,1). В результате вторая функция работает в 2 раза быстрее, т.к. ей не требуется проводить дополнительное вычисление выражения внутри добавления элемента в массив. 

Если сравнивать одинаковые по реализации функции с numpy и встроенными средствами python, то время отличается в разной степени. Встроенные средства python выигрывают по времени на коротких выборках, но проигрывают на длинных.

## Часть 2: генерация двумерного массива с помощью numpy и встроенных средств python

будем сравнивать 2 функции с одинаковыми условиями: диапазон генерации случайных чисел: [0, 1), т.е. дефолтные условия функции

Данные функции можно использовать для генерации как двумерых массивов, так и для n - мерных.

In [ ]:
def gener_d2_massive_np():
  n = [0, 0]
  n[0], n[1] = int(input(
      'введите количество элементов массива ')), int(input(
          'введите размерность массива '))
  tic = time.perf_counter_ns() # старт таймера
  # n подает в функцию 2 числа: первое - длина массива, второе - n-мерность массива
  d2 = np.random.sample(n)
  tac = time.perf_counter_ns()
  if len(d2) > 10:
    print("Random number list is : ", d2[0:5], '...', d2[-6:-1], sep = '\n')
  else:
    print ("Random number list is : ", d2, sep = '\n')  # выводим массив пользователю
  print(f"Создание массива заняло {tac-tic} нсек")
  return d2

In [ ]:
def gener_d2_massive_py():
  n = [0, 0]
  n[0], n[1] = int(input('введите количество элементов массива ')), int(
      input('введите размерность массива '))
  tic = time.perf_counter_ns() # старт таймера
  d2 = []
  for i in range(n[0]):
    d2.append([])
    for j in range(n[1]):
      d2[i].append(random.uniform(0,1)) 
      """можно указать или задать первоначальные  числа для генерации случайных чисел,
         но по условию данной части этого делать не будем"""
  tac = time.perf_counter_ns() # 
  if len(d2) > 10:
    print("Random number list is : ", d2[0:5], '...', d2[-6:-1], sep = '\n')
  else:
    print ("Random number list is : ", d2, sep = '\n')  # выводим массив пользователю
  print(f"Создание массива заняло {tac-tic} нсек")
  return d2

# генерируем и сравниваем массивы в 100 элементов

с помощью numpy

In [ ]:
gener_d2_massive_np()

введите количество элементов массива 100
введите размерность массива 2
Random number list is : 
[[0.25719779 0.72907931]
 [0.11434187 0.60006194]
 [0.55681182 0.63651665]
 [0.20992755 0.5297771 ]
 [0.04745534 0.18779603]]
...
[[0.40718438 0.22518779]
 [0.44831377 0.08768367]
 [0.77128362 0.97337603]
 [0.92762791 0.02096295]
 [0.12963547 0.05876661]]
Создание массива заняло 24531 нсек


с помощью встроенных средств python

In [ ]:
gener_d2_massive_py()

введите количество элементов массива 100
введите размерность массива 2
Random number list is : 
[[0.16359967158432087, 0.5486246381591015], [0.6095076147694523, 0.33004624273398553], [0.4036555779430806, 0.13072754715305734], [0.32565310891130317, 0.9316403316283483], [0.22243743748416978, 0.5941069098123465]]
...
[[0.3901691023204559, 0.8365749162913128], [0.5611051705694681, 0.009127887301314419], [0.527674888858152, 0.1090734595345415], [0.8527996070725177, 0.6477248762604386], [0.8676883577535335, 0.3293465128302068]]
Создание массива заняло 117080 нсек


# генерируем и сравниваем массивы в 1000 элементов

с помощью numpy

In [ ]:
nupy = gener_d2_massive_np()

введите количество элементов массива 1000
введите размерность массива 2
Random number list is : 
[[0.23904293 0.89624047]
 [0.79338276 0.17551994]
 [0.52992471 0.36699985]
 [0.54854403 0.06033267]
 [0.96956396 0.16901895]]
...
[[0.23766731 0.31921773]
 [0.73453249 0.42962206]
 [0.10642161 0.13139366]
 [0.85878737 0.4323449 ]
 [0.35059698 0.1388432 ]]
Создание массива заняло 32090 нсек


с помощью встроенных средств python

In [ ]:
pypy = gener_d2_massive_py()

введите количество элементов массива 1000
введите размерность массива 2
Random number list is : 
[[0.5804863474877596, 0.10275052312838318], [0.9888481012615199, 0.4660049574029509], [0.43987201705662915, 0.5241237461952716], [0.825018982082167, 0.5107222456481358], [0.09716561189117634, 0.0635295552140216]]
...
[[0.40038276057089406, 0.267777471033095], [0.731284452027248, 0.7230235644873914], [0.3755704875784599, 0.7945228730757529], [0.8940073637451953, 0.638883742894965], [0.8799519789940773, 0.23683086585406798]]
Создание массива заняло 1204210 нсек


## генерируем и сравниваем массивы в 100000 элементов

с помощью numpy

In [ ]:
gener_d2_massive_np()

введите количество элементов массива 100000
введите размерность массива 2
Random number list is : 
[[0.16509291 0.51826191]
 [0.9142247  0.19191696]
 [0.95164952 0.32164584]
 [0.66353777 0.83654793]
 [0.86850237 0.76869148]]
...
[[0.11986129 0.29225782]
 [0.95642752 0.73575132]
 [0.03569388 0.57281419]
 [0.73996271 0.13733722]
 [0.26053905 0.1170998 ]]
Создание массива заняло 2036189 нсек


с помощью встроенных средств python

In [ ]:
gener_d2_massive_py()

введите количество элементов массива 100000
введите размерность массива 2
Random number list is : 
[[0.7113834103505081, 0.3084261549539197], [0.8984629844130325, 0.8941114042834007], [0.6296778237925912, 0.8967891041583782], [0.4912897412839158, 0.4165653674473533], [0.4181098562922074, 0.23723016702423494]]
...
[[0.7198787961375985, 0.8301863090808853], [0.5778823953193014, 0.8686624668356183], [0.6719743557110404, 0.2980294109912527], [0.05201842371011978, 0.6665525459299501], [0.8484380454709762, 0.059139911332128814]]
Создание массива заняло 144177169 нсек


# Математические операции

проводить операции будем на примере массива в 1000 элементов


операции с массивом numpy

In [ ]:
nupy  # вывод массива

array([[0.23904293, 0.89624047],
       [0.79338276, 0.17551994],
       [0.52992471, 0.36699985],
       ...,
       [0.85878737, 0.4323449 ],
       [0.35059698, 0.1388432 ],
       [0.4964932 , 0.22676099]])

In [ ]:
nupy * 5  # умножение на число

array([[1.19521464, 4.48120233],
       [3.96691379, 0.8775997 ],
       [2.64962354, 1.83499925],
       ...,
       [4.29393683, 2.16172451],
       [1.75298489, 0.69421598],
       [2.48246598, 1.13380495]])

In [ ]:
nupy + nupy  # сложение массивов 

array([[0.47808585, 1.79248093],
       [1.58676552, 0.35103988],
       [1.05984942, 0.7339997 ],
       ...,
       [1.71757473, 0.8646898 ],
       [0.70119396, 0.27768639],
       [0.99298639, 0.45352198]])

In [ ]:
nupy-nupy  # вычитание

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       ...,
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
nupy.shape  # вывод размеров

(1000, 2)

In [ ]:
nupy.dtype # вывод типа данных в массиве

dtype('float64')

In [ ]:
1/nupy # число на массив

array([[4.18334904, 1.11577198],
       [1.26042568, 5.6973584 ],
       [1.88706053, 2.72479676],
       ...,
       [1.16443259, 2.31296818],
       [2.85227786, 7.2023695 ],
       [2.01412629, 4.4099296 ]])

In [ ]:
nupy ** 0.5  # извлечение корня

array([[0.48892016, 0.94669978],
       [0.89072036, 0.418951  ],
       [0.72795928, 0.60580512],
       ...,
       [0.92670781, 0.65752939],
       [0.5921123 , 0.37261669],
       [0.70462273, 0.47619428]])

In [ ]:
nupy > pypy # сравнение массивов

array([[False,  True],
       [False, False],
       [ True, False],
       ...,
       [False, False],
       [False, False],
       [ True, False]])

чтобы комфортно выполнять операции с массивом,  полученным с помощью встроенных средств python, можно преобразовать его с помощью numpy к типу объекта numpy.adarray

In [ ]:
pypy  # исходный массив

[[0.5804863474877596, 0.10275052312838318],
 [0.9888481012615199, 0.4660049574029509],
 [0.43987201705662915, 0.5241237461952716],
 [0.825018982082167, 0.5107222456481358],
 [0.09716561189117634, 0.0635295552140216],
 [0.8718072844462401, 0.022423764181230266],
 [0.14020210893654084, 0.2856692136179295],
 [0.1999566422541389, 0.20149362902803625],
 [0.24544890740882963, 0.43146830639077915],
 [0.21038206867111375, 0.45424934042186527],
 [0.922940433575812, 0.12522644794656312],
 [0.40869769229181074, 0.28196216181579536],
 [0.12542251865670906, 0.8946363235789854],
 [0.40221177550350795, 0.34630921699491846],
 [0.006136447737275286, 0.3467864791187131],
 [0.07049823775710673, 0.17828918646752945],
 [0.08041065234777589, 0.6750633439072777],
 [0.5798375100061945, 0.18322509462348646],
 [0.8132357083729452, 0.3964821683814731],
 [0.9442448237591039, 0.2176617088754177],
 [0.2830741737218987, 0.008756805663044487],
 [0.02421763273557931, 0.16813814252768344],
 [0.7809143203305645, 0.61248

In [ ]:
type(pypy)

list

In [ ]:
pypy_np = np.array(pypy)  # преобразование типа объекта массива

In [ ]:
type(pypy_np)

numpy.ndarray

далее можно выполнять все те же операции, что и в предыдущем разделе